---
title: "Title"
author: "Sahil Maheshwari"
date: "`r Sys.Date()`"
output:
  html_document: default
  html_notebook:
    df_print: paged
    code_folding: "hide"
editor_options:
  chunk_output_type: inline
---

```{r, setup, include=FALSE}
options("scipen"=100, "digits"=4, "knitr.table.format"="pandoc")
```

```{r, global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = TRUE,
                      cache = FALSE, cache.lazy = FALSE,
                      tidy = TRUE, highlight = TRUE, collapse = TRUE,
                      fig.fullwidth=TRUE, fig.align = "center", fig.width = 10)
```

```{r, include=FALSE}
source("utils.R")
```

```{r}
temp <- read.csv()
```  

```{r}
# Code to show
```

```{r, include=FALSE}
# code not to show
```

Display Table:
```{r}
datatable(temp,
          options = list(
            dom = 't', 
            autoWidth = TRUE,
            columnDefs = list(list(width = '500px', targets = c(2))),
            scrollX = T,
            scrollCollapse = FALSE,
            paging = FALSE
            ))
```

```{r}
datatable(temp,
          filter = "top",
          options = list(
            autoWidth = TRUE,
            columnDefs = list(list(width = '500px', targets = c(2))),
            scrollX = T,
            scrollY = "500px",
            scrollCollapse = FALSE,
            paging = FALSE
            ))
```


```{r}
message("\nNo. of unique combinations of ISIN + Ticker + HOCountryName + CountryOfQuote: ", n_distinct(bx_stock_noNA$ISIN, bx_stock_noNA$Ticker, bx_stock_noNA$HOCountryName, bx_stock_noNA$CountryOfQuote))
```


